In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/admin/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/admin/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/admin/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/admin/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

In [3]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [4]:
import numpy as np
np.add(10,60)

70

In [7]:
#testing zero in given array
import numpy as np
a=np.array([2,4,6,8])
print("If none of the elements in array is zero")
print(np.all(a))

If none of the elements in array is zero
True


In [10]:
import numpy as np
x=([0,2,4,5])
print("If none of the elememts in array is zero")
print(np.any(x))

If none of the elememts in array is zero
True


In [2]:
import numpy as np
a=np.array([2,4,6,8])
print(a)
print(np.all(a))

[2 4 6 8]
True


In [7]:
import numpy as np
x=np.array([2,4,0,np.NaN,np.inf])
print(x)
print(np.isfinite(x))

[ 2.  4.  0. nan inf]
[ True  True  True False False]


In [8]:
import numpy as np
x=np.array([1,0,3,np.NaN,np.inf])
print(x)
print(np.isinf(x))

[ 1.  0.  3. nan inf]
[False False False False  True]


In [9]:
import numpy as np
x=([1,5,0,np.NaN,np.inf])
print(x)
print(np.isnan(x))

[1, 5, 0, nan, inf]
[False False False  True False]


In [13]:
import numpy as np
x=np.array([1+1, 1+0j, 5j,2.5,3,2])
print(np.iscomplex(x))
print(np.isreal(x))
print(np.isscalar(3))
print(np.isscalar([3,2]))

[False False  True False False False]
[ True  True False  True  True  True]
True
False


In [16]:
import numpy as np
x=np.array([2,6])
y=np.array([3,8])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[False False]
[False False]
[ True  True]
[ True  True]


In [18]:
import numpy as np
x=np.array([72,79,55,-100,-190])
y=np.array([56,79,65,100.0,-98])
print(x)
print(y)
print(np.equal(x,y))
print(np.allclose(x,y))

[  72   79   55 -100 -190]
[ 56.  79.  65. 100. -98.]
[False  True False False False]
False


In [1]:
import numpy as np
x=np.array([1,7,13,105])
print(x)
print("size of the memory")
print("%d bytes" %(x.size*x.itemsize))

[  1   7  13 105]
size of the memory
16 bytes


In [3]:
import numpy as np
x=np.zeros(10)
print(x)
y=np.ones(10)
print(y)
z=np.ones(10)*5
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
import numpy as np
x=np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
x=np.arange(20,51,2)
print(x)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [14]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
x=np.random.normal(0,1,1)
print(x)

[1.51363515]


In [19]:
x=np.random.normal(0,1,15)
print(x)

[ 2.13441913 -1.38972961  1.68119619  0.04927557  1.03751656  1.60109624
  0.5903278  -0.31189734  0.23760171 -0.05279049  0.04270896 -1.57322452
  0.04187936 -0.48924803  0.876707  ]


In [28]:
x=np.arange(10,55)
print(x[1:-1])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [43]:
a=np.arange(10,22).reshape((3,4))
print(a)
for x in np.nditer(a):
    print(x,end=" ")

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
10 11 12 13 14 15 16 17 18 19 20 21 

In [45]:
x=np.linspace(10,49,5)
print(x)

[10.   19.75 29.5  39.25 49.  ]


In [50]:
x=np.arange(21)
print("Original Vector")
print(x)
print("After changing the sign of the numbers")
x[(x>=9)&(x<=15)]*=-1
print(x)

Original Vector
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [52]:
x=np.random.randint(0,11,5)
print(x)

[ 7  1  5  4 10]


In [53]:
x=np.array([2,4,6,8])
print("Vector-1")
print(x)
y=np.array([1,3,5,7])
print("Vector-2")
print(y)
z=x*y
z

Vector-1
[2 4 6 8]
Vector-2
[1 3 5 7]


array([ 2, 12, 30, 56])

In [54]:
x=np.arange(10,22).reshape(3,4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [56]:
x=np.arange(10,22).reshape(3,4)
x
print("no.of columns and rows")
print(x.shape)

no.of columns and rows
(3, 4)


In [59]:
x=np.identity(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
x=np.ones((10,10))
x[1:-1, 1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
x=np.diag([1,2,3,4,5])
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [68]:
x=np.zeros((4,4))
x[::2, 1::2]=1
x[1::2, ::2]=1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [3]:
import numpy as np
x=np.random.random((3,3,3))
x

array([[[0.98722213, 0.32216002, 0.53960921],
        [0.40596165, 0.69515637, 0.70924748],
        [0.40193444, 0.22571571, 0.4832975 ]],

       [[0.31362172, 0.56482787, 0.87617196],
        [0.36603144, 0.2565868 , 0.37739755],
        [0.73624706, 0.80472866, 0.11816984]],

       [[0.05796662, 0.75722454, 0.49611919],
        [0.88787719, 0.13949233, 0.22529031],
        [0.01897883, 0.13924362, 0.69618589]]])

In [1]:
#fromiter
import numpy as np
a=np.array([10,20,30,40,50])
res=np.asarray(a, dtype="float", order="C")
print(res)

[10. 20. 30. 40. 50.]


In [11]:
#logspace
a=np.logspace(0,10,num=4,endpoint=False)
print(a)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07]


In [12]:
a=np.logspace(0,10,num=4,endpoint=False, base=2)
print(a)

[  1.           5.65685425  32.         181.01933598]


In [13]:
#stack
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
b=np.arange(3,9).reshape(2,3)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [29]:
np.stack([a,b])

array([[[0, 1, 2],
        [3, 4, 5]],

       [[3, 4, 5],
        [6, 7, 8]]])

In [31]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7, 8]])

In [33]:
np.stack([a,b],axis=2)

array([[[0, 3],
        [1, 4],
        [2, 5]],

       [[3, 6],
        [4, 7],
        [5, 8]]])

In [34]:
np.vstack([a,b])

array([[0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
#Copy
a=np.array([10,20,30,40])
c=a.copy()
c

array([10, 20, 30, 40])

In [44]:
#view
v=a.view()
v=[10,20,30,40]
v[3]=50
print(v)
print(a)

[10, 20, 30, 50]
[10 20 30 40]
